export const API_ENDPOINT = "https://api-testnet.empow.io"
export const BLOCKCHAIN_ENDPOINT = "https://node-testnet.empow.io"
export const SOCKET_ENDPOINT = "https://socket-testnet.empow.io"
export const EMPO_URL = "https://testnet.emworld.io"
export const IPFS_URL = "ipfs.infura.io"
export const IPFS_GATEWAY_URL = "https://ipfs.infura.io/ipfs/"
export const ADMIN_ADDRESS = "EM2ZsE41ZSeukSxhMyLsb3dZWP7fgFt43L7e5b9hXVBGPU7U4"
export const DEFAULT_NETWORK = "TESTNET"